#
## IMPORTANT NOTE
##
## This chart inherits from our common library chart. You can check the default values/options here:
## https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
##
image:
  repository: eikek0/sharry
  tag: 1.6.0
  pullPolicy: IfNotPresent

service:
  port:
    port: 9090

args:
- "/opt/sharry.conf"

# -- Full list of options https://eikek.github.io/sharry/doc/configure
# @default -- see URL to default config
config: {}

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: "2048m"
    nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
