{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the configMap to the additionalVolumes */}}
{{- define "sharry.configmap.volume" -}}
name: sharry-config
configMap:
  name: {{ template "common.names.fullname" . }}-config
{{- end -}}

{{- $volume := include "sharry.configmap.volume" . | fromYaml -}}
{{- if $volume -}}
    {{- $additionalVolumes := append .Values.additionalVolumes $volume }}
    {{- $_ := set .Values "additionalVolumes" (deepCopy $additionalVolumes) -}}
{{- end -}}

{{/* Append the configMap volume to the additionalVolumeMounts */}}
{{- define "sharry.configmap.volumeMount" -}}
name: sharry-config
mountPath: /opt/sharry.conf
subPath: sharry.conf
{{- end -}}

{{- $volumeMount := include "sharry.configmap.volumeMount" . | fromYaml -}}
{{- if $volumeMount -}}
    {{- $additionalVolumeMounts := append .Values.additionalVolumeMounts $volumeMount }}
    {{- $_ := set .Values "additionalVolumeMounts" (deepCopy $additionalVolumeMounts) -}}
{{- end -}}

{{/* Render the templates */}}
{{ include "common.all" . }}
