# Default values for smarter-device-manager.
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common

controllerType: daemonset

image:
  repository: registry.gitlab.com/arm-research/smarter/smarter-device-manager
  tag: 1.1.2
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

# Path to your zigbee device in the container
additionalVolumeMounts:
  - name: host-dev
    mountPath: /dev
  - name: host-sys
    mountPath: /sys
  - name: host-kubelet-sockets
    mountPath: /var/lib/kubelet/device-plugins

additionalVolumes:
  - name: host-dev
    hostPath:
      path: /dev
  - name: host-sys
    hostPath:
      path: /sys
  - name: host-kubelet-sockets
    hostPath:
      path: /var/lib/kubelet/device-plugins

# smarter-device-manager configuration settings
config:
#   - devicematch: ^snd$
#     nummaxdevices: 20
#   - devicematch: ^ttyUSB.*$
#     nummaxdevices: 1
